// --------------------------------------------------------------------------------------------------------------------
// <copyright company="Aspose" file="ApiBase.cs">
//   Copyright (c) 2020 Aspose.Slides for Cloud
// </copyright>
// <summary>
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
// 
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
// 
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.
// </summary>
// --------------------------------------------------------------------------------------------------------------------


#ifndef _ClassRegistry_H_
#define _ClassRegistry_H_

#include <cpprest/details/basic_types.h>
#include <cpprest/json.h>
#include <map>
#include <boost/algorithm/string.hpp>
#include <boost/algorithm/string/replace.hpp>
#include "model/AccessPermissions.h"
#include "model/ApiInfo.h"
#include "model/ArrowHeadProperties.h"
#include "model/Axes.h"
#include "model/Axis.h"
#include "model/AxisType.h"
#include "model/BlurEffect.h"
#include "model/Camera.h"
#include "model/ChartCategory.h"
#include "model/ChartLinesFormat.h"
#include "model/ChartSeriesGroup.h"
#include "model/ChartTitle.h"
#include "model/ChartWall.h"
#include "model/ChartWallType.h"
#include "model/CommonSlideViewProperties.h"
#include "model/CustomDashPattern.h"
#include "model/DataPoint.h"
#include "model/DiscUsage.h"
#include "model/Effect.h"
#include "model/EffectFormat.h"
#include "model/EntityExists.h"
#include "model/Error.h"
#include "model/ErrorDetails.h"
#include "model/ExportFormat.h"
#include "model/ExportOptions.h"
#include "model/FileVersions.h"
#include "model/FilesList.h"
#include "model/FilesUploadResult.h"
#include "model/FillFormat.h"
#include "model/FillOverlayEffect.h"
#include "model/FontData.h"
#include "model/FontFallbackRule.h"
#include "model/FontSet.h"
#include "model/FontSubstRule.h"
#include "model/FontsData.h"
#include "model/GeometryPath.h"
#include "model/GeometryPaths.h"
#include "model/GlowEffect.h"
#include "model/GradientFillStop.h"
#include "model/Hyperlink.h"
#include "model/IShapeExportOptions.h"
#include "model/ImageExportFormat.h"
#include "model/ImageTransformEffect.h"
#include "model/InnerShadowEffect.h"
#include "model/Input.h"
#include "model/InputFile.h"
#include "model/InteractiveSequence.h"
#include "model/Legend.h"
#include "model/LightRig.h"
#include "model/LineFormat.h"
#include "model/MathElement.h"
#include "model/MathParagraph.h"
#include "model/MergingSource.h"
#include "model/NormalViewRestoredProperties.h"
#include "model/NotesSlideExportFormat.h"
#include "model/ObjectExist.h"
#include "model/OrderedMergeRequest.h"
#include "model/OuterShadowEffect.h"
#include "model/OutputFile.h"
#include "model/PathSegment.h"
#include "model/Pipeline.h"
#include "model/PlotArea.h"
#include "model/PortionFormat.h"
#include "model/PresentationToMerge.h"
#include "model/PresentationsMergeRequest.h"
#include "model/PresetShadowEffect.h"
#include "model/ReflectionEffect.h"
#include "model/ResourceBase.h"
#include "model/ResourceUri.h"
#include "model/Series.h"
#include "model/SeriesMarker.h"
#include "model/ShapeBevel.h"
#include "model/ShapeExportFormat.h"
#include "model/ShapeImageExportOptions.h"
#include "model/ShapeThumbnailBounds.h"
#include "model/ShapeType.h"
#include "model/ShapesAlignmentType.h"
#include "model/SlideCommentBase.h"
#include "model/SlideExportFormat.h"
#include "model/SmartArtNode.h"
#include "model/SoftEdgeEffect.h"
#include "model/SpecialSlideType.h"
#include "model/StorageExist.h"
#include "model/StorageFile.h"
#include "model/TableCell.h"
#include "model/TableColumn.h"
#include "model/TableRow.h"
#include "model/Task.h"
#include "model/TextBounds.h"
#include "model/TextFrameFormat.h"
#include "model/TextItem.h"
#include "model/ThreeDFormat.h"
#include "model/AccentElement.h"
#include "model/AddLayoutSlide.h"
#include "model/AddMasterSlide.h"
#include "model/AddShape.h"
#include "model/AddSlide.h"
#include "model/AlphaBiLevelEffect.h"
#include "model/AlphaCeilingEffect.h"
#include "model/AlphaFloorEffect.h"
#include "model/AlphaInverseEffect.h"
#include "model/AlphaModulateEffect.h"
#include "model/AlphaModulateFixedEffect.h"
#include "model/AlphaReplaceEffect.h"
#include "model/ArcToPathSegment.h"
#include "model/ArrayElement.h"
#include "model/BarElement.h"
#include "model/Base64InputFile.h"
#include "model/BiLevelEffect.h"
#include "model/BlockElement.h"
#include "model/BlurImageEffect.h"
#include "model/BorderBoxElement.h"
#include "model/BoxElement.h"
#include "model/ClosePathSegment.h"
#include "model/ColorChangeEffect.h"
#include "model/ColorReplaceEffect.h"
#include "model/ColorScheme.h"
#include "model/CubicBezierToPathSegment.h"
#include "model/DelimiterElement.h"
#include "model/Document.h"
#include "model/DocumentProperties.h"
#include "model/DocumentProperty.h"
#include "model/DuotoneEffect.h"
#include "model/FileVersion.h"
#include "model/FillOverlayImageEffect.h"
#include "model/FontScheme.h"
#include "model/FormatScheme.h"
#include "model/FractionElement.h"
#include "model/FunctionElement.h"
#include "model/GradientFill.h"
#include "model/GrayScaleEffect.h"
#include "model/GroupingCharacterElement.h"
#include "model/HeaderFooter.h"
#include "model/HslEffect.h"
#include "model/Html5ExportOptions.h"
#include "model/HtmlExportOptions.h"
#include "model/Image.h"
#include "model/ImageExportOptionsBase.h"
#include "model/Images.h"
#include "model/LayoutSlide.h"
#include "model/LayoutSlides.h"
#include "model/LeftSubSuperscriptElement.h"
#include "model/LimitElement.h"
#include "model/LineToPathSegment.h"
#include "model/LuminanceEffect.h"
#include "model/MasterSlide.h"
#include "model/MasterSlides.h"
#include "model/MatrixElement.h"
#include "model/Merge.h"
#include "model/MoveToPathSegment.h"
#include "model/NaryOperatorElement.h"
#include "model/NoFill.h"
#include "model/NotesSlide.h"
#include "model/NotesSlideHeaderFooter.h"
#include "model/OneValueChartDataPoint.h"
#include "model/OneValueSeries.h"
#include "model/Paragraph.h"
#include "model/Paragraphs.h"
#include "model/PathInputFile.h"
#include "model/PathOutputFile.h"
#include "model/PatternFill.h"
#include "model/PdfExportOptions.h"
#include "model/PictureFill.h"
#include "model/Placeholder.h"
#include "model/Placeholders.h"
#include "model/Portion.h"
#include "model/Portions.h"
#include "model/PptxExportOptions.h"
#include "model/ProtectionProperties.h"
#include "model/QuadraticBezierToPathSegment.h"
#include "model/RadicalElement.h"
#include "model/RemoveShape.h"
#include "model/RemoveSlide.h"
#include "model/ReorderSlide.h"
#include "model/ReplaceText.h"
#include "model/RequestInputFile.h"
#include "model/ResetSlide.h"
#include "model/ResponseOutputFile.h"
#include "model/RightSubSuperscriptElement.h"
#include "model/Save.h"
#include "model/SaveShape.h"
#include "model/SaveSlide.h"
#include "model/ScatterChartDataPoint.h"
#include "model/Section.h"
#include "model/Sections.h"
#include "model/ShapeBase.h"
#include "model/Shapes.h"
#include "model/Slide.h"
#include "model/SlideAnimation.h"
#include "model/SlideBackground.h"
#include "model/SlideComment.h"
#include "model/SlideComments.h"
#include "model/SlideModernComment.h"
#include "model/SlideProperties.h"
#include "model/Slides.h"
#include "model/SolidFill.h"
#include "model/SplitDocumentResult.h"
#include "model/SubscriptElement.h"
#include "model/SuperscriptElement.h"
#include "model/SvgExportOptions.h"
#include "model/SwfExportOptions.h"
#include "model/TextElement.h"
#include "model/TextItems.h"
#include "model/Theme.h"
#include "model/TintEffect.h"
#include "model/UpdateBackground.h"
#include "model/UpdateShape.h"
#include "model/VideoExportOptions.h"
#include "model/ViewProperties.h"
#include "model/XYSeries.h"
#include "model/XamlExportOptions.h"
#include "model/XpsExportOptions.h"
#include "model/BubbleChartDataPoint.h"
#include "model/BubbleSeries.h"
#include "model/Chart.h"
#include "model/DocumentReplaceResult.h"
#include "model/GeometryShape.h"
#include "model/GifExportOptions.h"
#include "model/GraphicalObject.h"
#include "model/GroupShape.h"
#include "model/ImageExportOptions.h"
#include "model/OleObjectFrame.h"
#include "model/ScatterSeries.h"
#include "model/SlideReplaceResult.h"
#include "model/SmartArt.h"
#include "model/SummaryZoomFrame.h"
#include "model/Table.h"
#include "model/TiffExportOptions.h"
#include "model/ZoomObject.h"
#include "model/AudioFrame.h"
#include "model/Connector.h"
#include "model/PictureFrame.h"
#include "model/SectionZoomFrame.h"
#include "model/Shape.h"
#include "model/SmartArtShape.h"
#include "model/VideoFrame.h"
#include "model/ZoomFrame.h"
#include "model/SummaryZoomSection.h"

namespace asposeslidescloud {
namespace api {

using namespace asposeslidescloud::model;

class ClassRegistry
{
public:
	static std::shared_ptr<void> deserialize(utility::string_t className, web::json::value json);
private:
	static utility::string_t getSubclass(utility::string_t className, web::json::value json);
	static std::shared_ptr<void> deserializeSubclass(utility::string_t className, web::json::value json);

	static std::map<utility::string_t, utility::string_t> s_hierarchy;
	static std::map<utility::string_t, std::map<utility::string_t, utility::string_t>> s_determiners;
};
}
}

#endif /* _ApiClient_H_ */
